/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_stojan_pasbox_argon2_NativeArgon2 */

#ifndef _Included_me_stojan_pasbox_argon2_NativeArgon2
#define _Included_me_stojan_pasbox_argon2_NativeArgon2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_stojan_pasbox_argon2_NativeArgon2
 * Method:    nhash
 * Signature: (IIIII[B[B[B)V
 */
JNIEXPORT void JNICALL Java_me_stojan_pasbox_argon2_NativeArgon2_nhash
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
